version: '3'
services:
  kibana:
    image: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:5
  node:
    image: node:9
    working_dir: /home/node/app
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - ELASTIC_HOST=${ELASTIC_HOST}
      - AWS_KEY=${AWS_KEY}
      - AWS_SECRET=${AWS_SECRET}
    links:
      - elasticsearch
    ports:
      - 83:80
    volumes:
      - ./:/home/node/app
    command: 'yarn start'
