version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.1
    ports:
      - 85:5601
    links:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  node:
    image: node:9
    working_dir: /home/node/app
    environment:
      - ELASTIC_HOST=${ELASTIC_HOST}
      - AWS_KEY=${AWS_KEY}
      - AWS_SECRET=${AWS_SECRET}
      - BUGS_KEY=${BUGS_KEY}
      - BUGS_SECRET=${BUGS_SECRET}
      - TEST_ACCOUNT_ID=${TEST_ACCOUNT_ID}
      - TEST_APPLICATION_ID=${TEST_APPLICATION_ID}
    links:
      - elasticsearch
    ports:
      - 83:3000
    volumes:
      - ./:/home/node/app
    command: ['./wait-for-it.sh', 'elasticsearch:9200', '--', 'yarn', 'start']
